from flask import Blueprint, request, jsonify, session
from core import database_mgr, analyzer
from routes import require_login

analysis_bp = Blueprint("analysis", __name__)
"""
Module: analysis.py
Layer : API Routing & Data Adapter Layer

- Establishes the '/analysis' endpoint for the React frontend.
- Enforces data sanitization and strict type safety on incoming JSON payloads.
- Acts as a Data Adapter: Normalizes and flattens complex nested clinical data 
  generated by the core algorithm into strict structures expected by the UI.
"""


@analysis_bp.route("/analysis", methods=["POST"])
@require_login
def analyze():
    # INTEGRATION & SECURITY LAYER
    # Incoming JSON payload is validated. Empty or malformed requests are
    # intercepted with a 400 Bad Request to ensure API security and data integrity.

    body = request.get_json() or {}
    drug_entries = body.get("drugs", [])

    if not drug_entries:
        return jsonify({"error": "no drugs provided"}), 400

    # The authenticated patient's medical profile is securely retrieved from the SQLite database.

    patient = database_mgr.get_patient(session["username"])
    if patient is None:
        return jsonify({"error": "user not found"}), 404

    import os
    drugs_path = os.path.join(os.path.dirname(__file__), '..', 'drugs.json')
    drug_db = database_mgr.load_drug_database(drugs_path)

    drug_objects = []
    daily_doses = {}
    invalid = []

    # DATA SANITIZATION & TYPE SAFETY
    # Hidden whitespaces in drug names are stripped. The incoming daily dose
    # is explicitly cast to a float to prevent TypeErrors during the core mathematical computations.

    for entry in drug_entries:
        name = entry.get("name", "").strip()
        if not name:
            continue
        if name not in drug_db:
            invalid.append(name)
            continue
        drug_objects.append(drug_db[name])

        try:
            daily_doses[name] = float(entry.get("daily_dose", 0))
        except (ValueError, TypeError):
            daily_doses[name] = 0.0

    if invalid:
        return jsonify({"error": f"unknown drugs: {invalid}"}), 400

    # The core analysis engine is triggered independently.
    raw_report = analyzer.analyze(patient, drug_objects, daily_doses)

    # DATA NORMALIZATION (ADAPTER PATTERN)
    # The raw clinical report generated by the core analyzer is processed here.
    # Complex nested data concerning patient risks, serotonin syndrome, etc.,
    # are flattened into a strict string array required by the React frontend's state.
    flat_warnings = []

    for w in raw_report.get("dose_assessments", []):
        flat_warnings.append(str(w))

    for w in raw_report.get("food_warnings", []):
        flat_warnings.append(str(w))

    for key in ["patient_risks", "serotonin_syndrome", "therapeutic_duplication",
                "additive_side_effects", "discontinuation_risks", "sex_specific_risks",
                "lifestyle_interactions", "age_eligibility"]:
        for w in raw_report.get(key, []):
            flat_warnings.append(str(w))

    # FRONTEND OBJECT MAPPING
    # Cumulative enzyme conflicts (e.g., CYP2D6, CYP3A4) are mapped into specific JSON objects
    # ({"drugs": [...], "shared_pathway": ...}).
    # This guarantees compatibility with the frontend's Interaction Card UI components.

    enzymes_list = ["CYP2D6", "CYP3A4", "CYP2C19", "CYP2C9", "CYP1A2", "CYP2B6"]

    for item in raw_report.get("interactions", []):
        explanation = item.get("explanation", "")
        severity = item.get("severity", "DANGER")

        flat_warnings.append(f"{severity}: {explanation}")

        involved = [d.name for d in drug_objects if d.name.lower() in explanation.lower()]
        if len(involved) < 2:
            involved = [d.name for d in drug_objects]
            while len(involved) < 2:
                involved.append("Unknown Drug")

        shared = "CYP Pathway"
        for e in enzymes_list:
            if e.lower() in explanation.lower():
                shared = e
                break

        flat_warnings.append({
            "drugs": involved[:2],
            "shared_pathway": shared,
            "severity": severity
        })

    for item in raw_report.get("substrate_saturation", []):
        explanation = item.get("explanation", "")
        severity = item.get("severity", "INFO")

        flat_warnings.append(f"{severity}: {explanation}")

        involved = [d.name for d in drug_objects if d.name.lower() in explanation.lower()]
        if len(involved) < 2:
            involved = [d.name for d in drug_objects]
            while len(involved) < 2:
                involved.append("Unknown Drug")

        shared = "CYP Pathway"
        for e in enzymes_list:
            if e.lower() in explanation.lower():
                shared = e
                break

        flat_warnings.append({
            "drugs": involved[:2],
            "shared_pathway": shared,
            "severity": severity
        })

    # DATABASE PERSISTENCE & RESPONSE
    # The finalized, normalized report is securely saved into the SQLite history
    # table for future retrieval, followed by returning an HTTP 200 JSON response.
    final_payload = {
        "warnings": flat_warnings,
        "drugs": [d.name for d in drug_objects]
    }
    database_mgr.save_history(session["username"], final_payload)
    return jsonify(final_payload)