from flask import Blueprint, request, jsonify, session
from core import database_mgr, analyzer
from routes import require_login

analysis_bp = Blueprint("analysis", __name__)
"""
Module: analysis.py
Layer : API Routing & Data Adapter Layer

- Establishes the '/analysis' endpoint for the React frontend.
- Enforces data sanitization and strict type safety on incoming JSON payloads.
- Acts as a Data Adapter: Normalizes and flattens complex nested clinical data 
  generated by the core algorithm into strict structures expected by the UI.
"""


@analysis_bp.route("/analysis", methods=["POST"])
@require_login
def analyze():
    body = request.get_json() or {}
    drug_entries = body.get("drugs", [])

    if not drug_entries:
        return jsonify({"error": "no drugs provided"}), 400

    patient = database_mgr.get_patient(session["username"])
    if patient is None:
        return jsonify({"error": "user not found"}), 404

    import os
    drugs_path = os.path.join(os.path.dirname(__file__), '..', 'drugs.json')
    drug_db = database_mgr.load_drug_database(drugs_path)

    drug_objects = []
    daily_doses = {}
    flat_warnings = []

    for entry in drug_entries:
        original_name = entry.get("name", "").strip()
        name_lower = original_name.lower()

        if not name_lower:
            continue

        # Guard (Koruyucu) Katmanı: Veritabanında yoksa analizi durdur
        if name_lower not in drug_db:
            return jsonify({
                "error": f"'{original_name}' is not in our clinical database. Please select only supported medications."
            }), 400

        actual_drug = drug_db[name_lower]
        drug_objects.append(actual_drug)

        try:
            dose = float(entry.get("daily_dose", 0))
        except (ValueError, TypeError):
            dose = 0.0

        if dose <= 0:
            return jsonify({"error": f"dose for {actual_drug.name} cannot be zero or negative"}), 400

        daily_doses[actual_drug.name] = dose

    # Analiz Engine
    raw_report = analyzer.analyze(patient, drug_objects, daily_doses)

    # DATA NORMALIZATION (ADAPTER PATTERN)
    # The raw clinical report generated by the core analyzer is processed here.
    # Complex nested data concerning patient risks, serotonin syndrome, etc.,
    # are flattened into a strict string array required by the React frontend's state.
    flat_warnings = []

    for w in raw_report.get("dose_assessments", []):
        flat_warnings.append(str(w))

    for w in raw_report.get("food_warnings", []):
        flat_warnings.append(str(w))

    for key in ["patient_risks", "serotonin_syndrome", "therapeutic_duplication",
                "additive_side_effects", "discontinuation_risks", "sex_specific_risks",
                "lifestyle_interactions", "age_eligibility"]:
        for w in raw_report.get(key, []):
            flat_warnings.append(str(w))

    # FRONTEND OBJECT MAPPING
    # Cumulative enzyme conflicts (e.g., CYP2D6, CYP3A4) are mapped into specific JSON objects
    # ({"drugs": [...], "shared_pathway": ...}).
    # This guarantees compatibility with the frontend's Interaction Card UI components.

    enzymes_list = ["CYP2D6", "CYP3A4", "CYP2C19", "CYP2C9", "CYP1A2", "CYP2B6"]

    for item in raw_report.get("interactions", []):
        flat_warnings.append({
            "type": "interaction",
            "drugs": item.get("involved_drugs", []),
            "shared_pathway": item.get("pathway", "CYP Pathway"),
            "severity": item.get("severity", "DANGER"),
            "message": item.get("explanation", "")
        })

    for item in raw_report.get("substrate_saturation", []):
        flat_warnings.append({
            "type": "saturation",
            "severity": item.get("severity", "INFO"),
            "message": item.get("explanation", "")
        })

    # DATABASE PERSISTENCE & RESPONSE
    # The finalized, normalized report is securely saved into the SQLite history
    # table for future retrieval, followed by returning an HTTP 200 JSON response.
    final_payload = {
        "warnings": flat_warnings,
        "drugs": [f"{d.name} . {daily_doses.get(d.name, 0)} mg" for d in drug_objects]
    }
    database_mgr.save_history(session["username"], final_payload)
    return jsonify(final_payload)


@analysis_bp.route("/conditions", methods=["GET"])
def get_available_conditions():
    """
    =========================================================================
    DYNAMIC CONDITIONS ENDPOINT
    Parses the drugs.json knowledge base dynamically to extract all unique
    risk factors. Prevents hardcoding in the frontend.
    =========================================================================
    """
    import os
    drugs_path = os.path.join(os.path.dirname(__file__), '..', 'drugs.json')
    drug_db = database_mgr.load_drug_database(drugs_path)

    conditions_set = set()
    for drug in drug_db.values():
        for condition in drug.risk_factors.keys():
            conditions_set.add(condition)

    # conditions_set is turned into the list and sorted alphabetically, returned in the JSON format.
    return jsonify(sorted(list(conditions_set)))